replicaCount: 1

image:
  repository: cp.icr.io/cp/ibm-watsonx-assistant-for-z/wxa4z-system-automation-netview-agent
  tag: v3.2.0@sha256:6fd8a8a67f5c1625916ffaab7ac5ece281c874b8e0664f7ba951535c75437424
  pullPolicy: Always

service:
  name: wxa4z-automation-insight-agent-service
  ports:
    name: http
    protocol: TCP
    port: 8080
    targetPort: 8050

route:
  name: wxa4z-automation-insight-agent-route
  annotations:
    hostGenerated: "true"
  serviceName: wxa4z-automation-insight-agent-service
  weight: 100
  targetPort: http
  tls:
    termination: edge
    secretName: wxa4z-agents-tls-secret
    enableTlsCertMount: false # Set to true to mount TLS certs from secret when deploying standalone helm-chart.
env:
  WATSONX_DEPLOYMENT_SPACE_ID: ""
  WATSONX_ML_URL: ""
  ONPREM_WML_INSTANCE_ID: openshift
  WATSONX_MODEL_ID: meta-llama/llama-3-3-70b-instruct
  DEPLOYMENT_TYPE: on-prem
  # CPD_VERSION, needed for on-prem deployments.Example(5.1)
  CPD_VERSION: "5.2"
  LANGFUSE_HOST: "LANGFUSE_HOST"
  LANGFUSE_TRACING_ENABLED: false
  LANGFUSE_ENABLED: false
  MAX_LLM_CONTEXT_MESSAGES_COUNT: 50
  MODEL_CATALOG_PATH: /opt/app-root/src/model_catalog.yaml
  ZCHATOPS_MCP_URL: "http://wxa4z-zchatops-mcp-server-service.wxa4z-aiops.svc.cluster.local:8081"

secrets:
  name: wxa4z-automation-insight-agent-agent-secrets
  createSecret: true
  data:
    # CPD USERNAME,  Needed for on-prem only.(set it to empty for cloud)
    CPD_USERNAME: cpadmin
    # Set this to CPD API Key for on-prem Install, For IBM Cloud, use IBM Cloud IAM API KEY
    WATSONX_API_KEY: ""
    # External App Credential specific to aiops-agent
    AIOPS_BASE_URL: ""
    AIOPS_TOKEN: ""
    # This is the auth token for communication with agent. This Key field(value can be anything api_key or bearer token) is referred by agent-controller for agent registration with wxo
    AGENT_AUTH_TOKEN: ""
    LANGFUSE_SECRET_KEY: LANGFUSE_SECRET_KEY
    LANGFUSE_PUBLIC_KEY: LANGFUSE_PUBLIC_KEY

imagePullSecrets:
  - name: wxa4z-image-pull-secret

resources:
  limits:
    cpu: "2"
    memory: "2Gi"
  requests:
    cpu: "200m"
    memory: "1Gi"

pvc:
  storageClass: "ocs-storagecluster-cephfs"
  accessModes:
    - ReadWriteOnce
  enabled: true
  size: 8Gi

networkPolicy:
  name: wxa4z-automation-insight-agent-network-policy
  egress:
    - {}
  ingress:
    - {}

bootstrapJob:
  enabled: true
  completions: 1
  parallelism: 1
  backoffLimit: 2
  activeDeadlineSeconds: 1800
  image:
    repository: cp.icr.io/cp/ibm-watsonx-assistant-for-z/wxa4z-agent-bootstrapper
    tag: v3.2.0@sha256:2957329a637d4ce4c21bbd1b88da77f050497883ce78cabc96afeb1d790425f5
    pullPolicy: Always
    overwrite: "true"
  imagePullSecrets:
    - name: wxa4z-image-pull-secret
  secret:
    dev_mode: false # Set this to true if you are installing subchart independently. When using wxa4z-agentic-suite, this should be false.
    name: automation-insight-agent-bootstrap-job-secret
    data:
      ORCHESTRATE_ENV_TYPE: cpd
      WATSONX_API_KEY: ""
      ORCHESTRATE_ENV_URL: ""
      CPD_USERNAME: cpadmin
  env:
    ORCHESTRATE_ENV_NAME: "wxo-live-instance"
    CONFIG_PATH: "/automation-insight-agent-bootstrap-config/automation_insight_agent_bootstrap_config.yaml"
    HOME: /opt/app-root/src
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "250m"
  serviceAccount:
    name: automation-insight-agent-bootstrap-job-sa
