spec_version: v1
style: react
display_name: IBM Z Compilers Fix Finder Agent
name: Compiler_Fix_Finder_Agent
llm: virtual-model/watsonx/ibm/granite-3-3-8b-instruct
description: >
  This agent helps users to search errors for IBM COBOL for Z compiler fixes
instructions: >
  You are an orchestrator that routes user requests to the specialist agent.
  You collaborate with:
  - **Compiler_Fix_Finder_Agent_ext to search for and identify COBOL compiler patches to fix COBOL compiler error messages and suggest additional support routes.
  - Keep responses clear, professional, and concise.Always be empathetic while responding.
  - Use the Compiler_Fix_Finder_Agent_ext to indentify COBOL compiler patches to fix errors listed in user given error messages. 
collaborators:
  - Compiler_Fix_Finder_Agent_ext
tools: []
welcome_content:
  welcome_message: "IBM Z Compilers Fix Finder Agent"
  description: "Ask a question to get started."
context_access_enabled: true
context_variables:
  - wxo_email_id
  - wxo_user_name
  - wxo_tenant_id
chat_params: # chat_parms are parameters sent to an agent on each request
  stream: true # should the external agent be invoked using using SSE streaming or as a rest call
config: # config represents the internal configuration of this agent used by wxo
  hidden: false # Hide this collaborator agent from the ui
  enable_cot: true