replicaCount: 1

image:
  repository: icr.io/wxa4z-agentic-dev-cr/cics-ai-agent
  tag: topology-1.2.0-RC3@sha256:5711401a26e7b159221f0f5f4ad4f6b5cca9573558da327dfb2d60ed82d409ee
  pullPolicy: Always

PDimage:
  repository: icr.io/wxa4z-agentic-dev-cr/cics-ai-agent
  tag: problem-determination-1.2.0-RC1@sha256:71d72b9f3cd3186d1efab885e87c0b604131d48f7f1f6ea550a4ce62df39fe72
  pullPolicy: Always

followupImage:
  repository: icr.io/wxa4z-agentic-dev-cr/cics-ai-agent
  tag: followup-1.2.0-RC3@sha256:f56a1d8d6242d5c7217db2efc4930cca6e38cdbf099188a51dc9f663f9524714
  pullPolicy: Always

TCimage:
  repository: icr.io/wxa4z-agentic-dev-cr/cics-ai-agent
  tag: tool-calling-agent-1.2.0-RC-LPAR-test@sha256:fcf86951af55e03b2ff648f6a767f09e09fd7f1db7635b7af66e54ed89a110af
  pullPolicy: Always

service:
  name: wxa4z-cics-service
  ports:
    name: http
    protocol: TCP
    port: 8080
    targetPort: 8000

PDservice:
  name: wxa4z-cics-pd-service
  ports:
    name: http
    protocol: TCP
    port: 8080
    targetPort: 8000

followupService:
  name: wxa4z-cics-followup-service
  ports:
    name: http
    protocol: TCP
    port: 8080
    targetPort: 8000
TCservice:
  name: wxa4z-cics-tc-service
  ports:
    name: http
    protocol: TCP
    port: 8080
    targetPort: 8000

route:
  name: wxa4z-cics-route
  annotations:
    hostGenerated: "true"
  serviceName: wxa4z-cics-service
  weight: 100
  targetPort: http
  tls:
    termination: edge
    secretName: wxa4z-agents-tls-secret
    enableTlsCertMount: false # Set to true to mount TLS certs from secret when deploying standalone helm-chart.

PDroute:
  name: wxa4z-cics-pd-route
  annotations:
    hostGenerated: "true"
  serviceName: wxa4z-cics-pd-service
  weight: 100
  targetPort: http
  tls:
    termination: edge
    secretName: wxa4z-agents-tls-secret
    enableTlsCertMount: false # Set to true to mount TLS certs from secret when deploying standalone helm-chart.

followupRoute:
  name: wxa4z-cics-followup-route
  annotations:
    hostGenerated: "true"
  serviceName: wxa4z-cics-followup-service
  weight: 100
  targetPort: http
  tls:
    termination: edge
    secretName: wxa4z-agents-tls-secret
    enableTlsCertMount: false # Set to true to mount TLS certs from secret when deploying standalone helm-chart.
TCroute:
  name: wxa4z-cics-tc-route
  annotations:
    hostGenerated: "true"
  serviceName: wxa4z-cics-tc-service
  weight: 100
  targetPort: http
  tls:
    termination: edge
    secretName: wxa4z-agents-tls-secret
    enableTlsCertMount: false # Set to true to mount TLS certs from secret when deploying standalone helm-chart.

env:
  # Required for on prem installations.
  WATSONX_DEPLOYMENT_SPACE_ID: ""
  # Set this to CPD Instance(https://cpd_instance.com) or IBM CLOUD WML Url for cloud deployment
  WATSONX_ML_URL: ""
  CPD_VERSION: "5.2"
  ONPREM_WML_INSTANCE_ID: openshift
  # This must be set to either "cloud" or "on-prem".
  DEPLOYMENT_TYPE: "on-prem"
  LANGFUSE_HOST: "LANGFUSE_HOST"
  LANGFUSE_TRACING_ENABLED: false
  ### Set this to the URL for the MCP server in CICS
  MCP_SERVER_URL: ""
  APPLID: ""
  ### set this to the model
  WATSONX_MODEL_ID: meta-llama/llama-3-3-70b-instruct
  MODEL_CATALOG_PATH: /home/agentserver/agents/prompt.yaml

secrets:
  name: wxa4z-cics-agent-secrets
  createSecret: true
  data:
    ### Set for on-prem deployments, leave blank otherwise.
    CPD_USERNAME: cpadmin
    ### Set this to CPD API Key for on-prem Install, For IBM Cloud, use IBM Cloud IAM API KEY
    WATSONX_API_KEY: ""
    ### Values set for zRAG
    WRAPPER_USERNAME: ""
    WRAPPER_PASSWORD: ""
    WRAPPER_URL: ""
    ### Set these to ingest documents on start-up
    INGESTION_URL: ""
    INGESTION_PASSWORD: ""
    ### Values fed through during deployment
    AGENT_ID: "wxa4z:cics:agent"
    AUTH_SERVICE_BASE_URL: "http://wxa4z-authorization-service.wxa4z-zad.svc.cluster.local:8080"
    AGENT_AUTH_TOKEN: ""
    ### Only set next 2 for cloud deployments, leave blank otherwise.
    WATSONX_PROJECT_URL: ""
    WATSONX_PROJECT_ID: ""
    ### Set these for tracing
    LANGFUSE_SECRET_KEY: LANGFUSE_SECRET_KEY
    LANGFUSE_PUBLIC_KEY: LANGFUSE_PUBLIC_KEY
    AGENT_ROUTER_PATH: "agents/topology_agent/router"

PDsecrets:
  name: wxa4z-cics-pd-agent-secrets
  createSecret: true
  data:
    ### Set for on-prem deployments, leave blank otherwise.
    CPD_USERNAME: cpadmin
    ### Set this to CPD API Key for on-prem Install, For IBM Cloud, use IBM Cloud IAM API KEY
    WATSONX_API_KEY: ""
    ### Values set for zRAG
    WRAPPER_USERNAME: ""
    WRAPPER_PASSWORD: ""
    WRAPPER_URL: ""
    ### Set these to ingest documents on start-up
    INGESTION_URL: ""
    INGESTION_PASSWORD: ""
    ### Set this to the URL for the MCP server in CICS
    MCP_SERVER_URL: MCP_SERVER_URL
    APPLID: "APPLID"
    ### Values fed through during deployment
    AGENT_ID: "wxa4z:cics:agent"
    AUTH_SERVICE_BASE_URL: "http://wxa4z-authorization-service.wxa4z-zad.svc.cluster.local:8080"
    AGENT_AUTH_TOKEN: "AGENT_AUTH_TOKEN"
    ### Only set next 2 for cloud deployments, leave blank otherwise.
    WATSONX_PROJECT_URL: "WATSONX_PROJECT_URL"
    WATSONX_PROJECT_ID: "WATSONX_PROJECT_ID"
    ### Set these for tracing
    LANGFUSE_SECRET_KEY: LANGFUSE_SECRET_KEY
    LANGFUSE_PUBLIC_KEY: LANGFUSE_PUBLIC_KEY
    AGENT_ROUTER_PATH: "agents/problem_determination_agent/router"
    SERVICE_ENDPOINT: ""
    INSECURE: "True"

followupSecrets:
  name: wxa4z-cics-followup-agent-secrets
  createSecret: true
  data:
    ### Set for on-prem deployments, leave blank otherwise.
    CPD_USERNAME: cpadmin
    ### Set this to CPD API Key for on-prem Install, For IBM Cloud, use IBM Cloud IAM API KEY
    WATSONX_API_KEY: ""
    ### Values set for zRAG
    WRAPPER_USERNAME: ""
    WRAPPER_PASSWORD: ""
    WRAPPER_URL: ""
    ### Set these to ingest documents on start-up
    INGESTION_URL: ""
    INGESTION_PASSWORD: ""
    ### Values fed through during deployment
    AGENT_ID: "wxa4z:cics:agent"
    AUTH_SERVICE_BASE_URL: "http://wxa4z-authorization-service.wxa4z-zad.svc.cluster.local:8080"
    AGENT_AUTH_TOKEN: ""
    ### Only set next 2 for cloud deployments, leave blank otherwise.
    WATSONX_PROJECT_URL: ""
    WATSONX_PROJECT_ID: ""
    ### Set these for tracing
    LANGFUSE_SECRET_KEY: LANGFUSE_SECRET_KEY
    LANGFUSE_PUBLIC_KEY: LANGFUSE_PUBLIC_KEY
    AGENT_ROUTER_PATH: "agents/followup_agent/router"

TCsecrets:
  name: wxa4z-cics-tc-agent-secrets
  createSecret: true
  data:
    ### Set for on-prem deployments, leave blank otherwise.
    CPD_USERNAME: cpadmin
    ### Set this to CPD API Key for on-prem Install, For IBM Cloud, use IBM Cloud IAM API KEY
    WATSONX_API_KEY: ""
    ### Values set for zRAG
    WRAPPER_USERNAME: ""
    WRAPPER_PASSWORD: ""
    WRAPPER_URL: ""
    ### Set these to ingest documents on start-up
    INGESTION_URL: ""
    INGESTION_PASSWORD: ""
    ### Set this to the URL for the MCP server in CICS
    MCP_SERVER_URL: MCP_SERVER_URL
    APPLID: "APPLID"
    ### Values fed through during deployment
    AGENT_ID: "wxa4z:cics:agent"
    AUTH_SERVICE_BASE_URL: "http://wxa4z-authorization-service.wxa4z-zad.svc.cluster.local:8080"
    AGENT_AUTH_TOKEN: "AGENT_AUTH_TOKEN"
    ### Only set next 2 for cloud deployments, leave blank otherwise.
    WATSONX_PROJECT_URL: "WATSONX_PROJECT_URL"
    WATSONX_PROJECT_ID: "WATSONX_PROJECT_ID"
    ### Set these for tracing
    LANGFUSE_SECRET_KEY: LANGFUSE_SECRET_KEY
    LANGFUSE_PUBLIC_KEY: LANGFUSE_PUBLIC_KEY
    AGENT_ROUTER_PATH: "agents/tool_calling_agent/router"
    SERVICE_ENDPOINT: ""
    INSECURE: "True"

imagePullSecrets:
  - name: cics-image-pull-secret

# This is the image pull secret for pulling the agent image from icr.io, replace registry.server, registry.username and registry.entitlementKey with your own values.
registry:
  name: cics-image-pull-secret
  createSecret: true
  server: icr.io
  username: iamapikey
  entitlementKey: ""

resources:
  limits:
    cpu: "2"
    memory: "2Gi"
  requests:
    cpu: "1"
    memory: "1Gi"

pvc:
  storageClass: "ocs-storagecluster-cephfs"
  accessModes:
    - ReadWriteOnce
  enabled: false
  size: 8Gi

PDpvc:
  name: cics-pd-agent-pvc
  storageClass: "ocs-storagecluster-cephfs"
  accessModes:
    - ReadWriteOnce
  enabled: false
  size: 8Gi

followupPvc:
  name: cics-followup-agent-pvc
  storageClass: "ocs-storagecluster-cephfs"
  accessModes:
    - ReadWriteOnce
  enabled: false
  size: 8Gi

TCpvc:
  name: cics-tc-agent-pvc
  storageClass: "ocs-storagecluster-cephfs"
  accessModes:
    - ReadWriteOnce
  enabled: false
  size: 8Gi

networkPolicy:
  name: wxa4z-cics-network-policy
  egress:
    - {}
  ingress:
    - {}

pdCertSecret:
  name: pd-custom-cert-secret
  cert: |
    -----BEGIN CERTIFICATE-----
    Replace this value with the certificate 
    you create to access your service endpoint.
    This secret can be manually updated in 
    your cluster after deployment. It is NOT 
    recommended that you store secrets in any 
    git repository. Restart your pod after 
    updating this secret to reflect changes.
    -----END CERTIFICATE-----

topologyCertSecret:
  name: topology-custom-cert-secret
  cert: |
    -----BEGIN CERTIFICATE-----
    Replace this value with the certificate 
    you create to access your service endpoint.
    This secret can be manually updated in 
    your cluster after deployment. It is NOT 
    recommended that you store secrets in any 
    git repository. Restart your pod after 
    updating this secret to reflect changes.
    -----END CERTIFICATE-----

followupCertSecret:
  name: followup-custom-cert-secret
  cert: |
    -----BEGIN CERTIFICATE-----
    Replace this value with the certificate 
    you create to access your service endpoint.
    This secret can be manually updated in 
    your cluster after deployment. It is NOT 
    recommended that you store secrets in any 
    git repository. Restart your pod after 
    updating this secret to reflect changes.
    -----END CERTIFICATE-----


tcCertSecret:
  name: tc-custom-cert-secret
  cert: |
    -----BEGIN CERTIFICATE-----
    Replace this value with the certificate 
    you create to access your service endpoint.
    This secret can be manually updated in 
    your cluster after deployment. It is NOT 
    recommended that you store secrets in any 
    git repository. Restart your pod after 
    updating this secret to reflect changes.
    -----END CERTIFICATE-----

PDnetworkPolicy:
  name: wxa4z-cics-pd-network-policy
  egress:
    - {}
  ingress:
    - {}

followupNetworkPolicy:
  name: wxa4z-cics-followup-network-policy
  egress:
    - {}
  ingress:
    - {}

TCnetworkPolicy:
  name: wxa4z-cics-tc-network-policy
  egress:
    - {}
  ingress:
    - {}

ilmtAnnotation:
  productID: "d86349db4b554664b9b681d0d7594fa5"
  productName: "IBM CICS Transaction Server agents for Z"
  productMetric: "FREE"
  productChargedContainers: "All"

bootstrapJob:
  enabled: true
  completions: 1
  parallelism: 1
  backoffLimit: 2
  activeDeadlineSeconds: 1800
  image:
    repository: na.artifactory.swg-devops.com/sys-nazare-cicd-team-wxo4z-docker-local/wxa4z-agent-bootstrapper
    tag: 3.1.3@sha256:b16b40acc5f51fff59ce5cd9311398df978397e13a92277b54f95709fd581ac1
    pullPolicy: Always
    overwrite: "true"
  imagePullSecrets:
    - name: wxa4z-image-pull-secret
  env:
    ORCHESTRATE_ENV_NAME: wxo-live-instance
    CONFIG_PATH: "/cics-agent-bootstrap-config/cics_agent_bootstrap_config.yaml"
    HOME: /opt/app-root/src
  secret:
    dev_mode: false # Set this to true if you are installing subchart independently. When using wxa4z-agentic-suite, this should be false.
    name: cics-agent-bootstrap-job-secret
    data:
      ORCHESTRATE_ENV_TYPE: cpd
      WATSONX_API_KEY: ""
      ORCHESTRATE_ENV_URL: ""
      CPD_USERNAME: cpadmin
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "250m"
  serviceAccount:
    name: cics-agent-bootstrap-job-sa
